### ISSUE TITLE
BoxTree study

### ISSUE THREAD

**Issue by tlechaux** [nexmicroservices/micromapper#5]
The goal is to find whether a open-source, language coherent library should be used to power the domain graph, or if a new library should be create from scratch

**Comment by ThomasDaubenton** [comment]
I think the best option would be to use a common js library to avoid complex implementation.

For example, we can use D3.js (https://www.d3-graph-gallery.com/treemap) or chart.js (https://codepen.io/ThomasDaubenton/pen/rNVoLbx)

**Comment by schaillon** [comment]
Usage of simple React Bootstrap component for the first iteration
